FROM continuumio/miniconda3

#更新apt-get源 使用163的源
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >/etc/apt/sources.list && \
    echo "deb http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list

RUN conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && \
    conda config --set show_channel_urls yes

RUN apt-get update --fix-missing && apt-get install supervisor -y

WORKDIR /opt

copy ./controller/requirements.txt /opt/requirements.txt
RUN conda install --file ./requirements.txt

ENV IPYTHONDIR=/opt/
CMD ["/usr/bin/supervisord", "-c", "./controller/supervisord.conf"]
RUN chmod 666 /opt/

COPY . /opt
